# Generated by Django 3.2.4 on 2023-03-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_distanceadditionalprice_distancebaseprice_pricingconfig_timemultiplierfactor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesPricing',
        ),
    ]
