# Generated by Django 3.2.4 on 2023-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
